#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPMMODELRUANGAN.Database
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MPMHRGA")]
	public partial class MPMHRGADataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMPMINFRUANGANHDR(MPMINFRUANGANHDR instance);
    partial void UpdateMPMINFRUANGANHDR(MPMINFRUANGANHDR instance);
    partial void DeleteMPMINFRUANGANHDR(MPMINFRUANGANHDR instance);
    partial void InsertMPMINFRUANGANDTL(MPMINFRUANGANDTL instance);
    partial void UpdateMPMINFRUANGANDTL(MPMINFRUANGANDTL instance);
    partial void DeleteMPMINFRUANGANDTL(MPMINFRUANGANDTL instance);
    #endregion
		
		public MPMHRGADataContext() :
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["MPMHRGA"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MPMHRGADataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MPMHRGADataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MPMHRGADataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MPMHRGADataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<MPMINFRUANGANHDR> MPMINFRUANGANHDRs
		{
			get
			{
				return this.GetTable<MPMINFRUANGANHDR>();
			}
		}
		
		public System.Data.Linq.Table<MPMINFRUANGANDTL> MPMINFRUANGANDTLs
		{
			get
			{
				return this.GetTable<MPMINFRUANGANDTL>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MPMINFRUANGANHDR")]
	public partial class MPMINFRUANGANHDR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _IDTHRUANGAN;
		
		private string _text;
		
		private string _description;
		
		private System.Nullable<System.DateTime> _startDate;
		
		private System.Nullable<System.DateTime> _endDate;
		
		private string _CREATEBY;
		
		private System.Nullable<System.DateTime> _CREATEDATE;
		
		private string _MODIFBY;
		
		private System.Nullable<System.DateTime> _MODIFDATE;
		
		private EntitySet<MPMINFRUANGANDTL> _MPMINFRUANGANDTLs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDTHRUANGANChanging(System.Guid value);
    partial void OnIDTHRUANGANChanged();
    partial void OntextChanging(string value);
    partial void OntextChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OnstartDateChanging(System.Nullable<System.DateTime> value);
    partial void OnstartDateChanged();
    partial void OnendDateChanging(System.Nullable<System.DateTime> value);
    partial void OnendDateChanged();
    partial void OnCREATEBYChanging(string value);
    partial void OnCREATEBYChanged();
    partial void OnCREATEDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCREATEDATEChanged();
    partial void OnMODIFBYChanging(string value);
    partial void OnMODIFBYChanged();
    partial void OnMODIFDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnMODIFDATEChanged();
    #endregion
		
		public MPMINFRUANGANHDR()
		{
			this._MPMINFRUANGANDTLs = new EntitySet<MPMINFRUANGANDTL>(new Action<MPMINFRUANGANDTL>(this.attach_MPMINFRUANGANDTLs), new Action<MPMINFRUANGANDTL>(this.detach_MPMINFRUANGANDTLs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTHRUANGAN", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid IDTHRUANGAN
		{
			get
			{
				return this._IDTHRUANGAN;
			}
			set
			{
				if ((this._IDTHRUANGAN != value))
				{
					this.OnIDTHRUANGANChanging(value);
					this.SendPropertyChanging();
					this._IDTHRUANGAN = value;
					this.SendPropertyChanged("IDTHRUANGAN");
					this.OnIDTHRUANGANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_text", DbType="VarChar(50)")]
		public string text
		{
			get
			{
				return this._text;
			}
			set
			{
				if ((this._text != value))
				{
					this.OntextChanging(value);
					this.SendPropertyChanging();
					this._text = value;
					this.SendPropertyChanged("text");
					this.OntextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="VarChar(250)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_startDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> startDate
		{
			get
			{
				return this._startDate;
			}
			set
			{
				if ((this._startDate != value))
				{
					this.OnstartDateChanging(value);
					this.SendPropertyChanging();
					this._startDate = value;
					this.SendPropertyChanged("startDate");
					this.OnstartDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> endDate
		{
			get
			{
				return this._endDate;
			}
			set
			{
				if ((this._endDate != value))
				{
					this.OnendDateChanging(value);
					this.SendPropertyChanging();
					this._endDate = value;
					this.SendPropertyChanged("endDate");
					this.OnendDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEBY", DbType="VarChar(50)")]
		public string CREATEBY
		{
			get
			{
				return this._CREATEBY;
			}
			set
			{
				if ((this._CREATEBY != value))
				{
					this.OnCREATEBYChanging(value);
					this.SendPropertyChanging();
					this._CREATEBY = value;
					this.SendPropertyChanged("CREATEBY");
					this.OnCREATEBYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATEDATE
		{
			get
			{
				return this._CREATEDATE;
			}
			set
			{
				if ((this._CREATEDATE != value))
				{
					this.OnCREATEDATEChanging(value);
					this.SendPropertyChanging();
					this._CREATEDATE = value;
					this.SendPropertyChanged("CREATEDATE");
					this.OnCREATEDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODIFBY", DbType="VarChar(50)")]
		public string MODIFBY
		{
			get
			{
				return this._MODIFBY;
			}
			set
			{
				if ((this._MODIFBY != value))
				{
					this.OnMODIFBYChanging(value);
					this.SendPropertyChanging();
					this._MODIFBY = value;
					this.SendPropertyChanged("MODIFBY");
					this.OnMODIFBYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODIFDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> MODIFDATE
		{
			get
			{
				return this._MODIFDATE;
			}
			set
			{
				if ((this._MODIFDATE != value))
				{
					this.OnMODIFDATEChanging(value);
					this.SendPropertyChanging();
					this._MODIFDATE = value;
					this.SendPropertyChanged("MODIFDATE");
					this.OnMODIFDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MPMINFRUANGANHDR_MPMINFRUANGANDTL", Storage="_MPMINFRUANGANDTLs", ThisKey="IDTHRUANGAN", OtherKey="IDTHRUANGAN")]
		public EntitySet<MPMINFRUANGANDTL> MPMINFRUANGANDTLs
		{
			get
			{
				return this._MPMINFRUANGANDTLs;
			}
			set
			{
				this._MPMINFRUANGANDTLs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MPMINFRUANGANDTLs(MPMINFRUANGANDTL entity)
		{
			this.SendPropertyChanging();
			entity.MPMINFRUANGANHDR = this;
		}
		
		private void detach_MPMINFRUANGANDTLs(MPMINFRUANGANDTL entity)
		{
			this.SendPropertyChanging();
			entity.MPMINFRUANGANHDR = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MPMINFRUANGANDTL")]
	public partial class MPMINFRUANGANDTL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _IDTHRUANGAN;
		
		private System.Guid _IDPARTICIPANT;
		
		private string _NPK;
		
		private string _CREATEBY;
		
		private System.Nullable<System.DateTime> _CREATEDATE;
		
		private string _MODIFBY;
		
		private System.Nullable<System.DateTime> _MODIFDATE;
		
		private EntityRef<MPMINFRUANGANHDR> _MPMINFRUANGANHDR;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDTHRUANGANChanging(System.Guid value);
    partial void OnIDTHRUANGANChanged();
    partial void OnIDPARTICIPANTChanging(System.Guid value);
    partial void OnIDPARTICIPANTChanged();
    partial void OnNPKChanging(string value);
    partial void OnNPKChanged();
    partial void OnCREATEBYChanging(string value);
    partial void OnCREATEBYChanged();
    partial void OnCREATEDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCREATEDATEChanged();
    partial void OnMODIFBYChanging(string value);
    partial void OnMODIFBYChanged();
    partial void OnMODIFDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnMODIFDATEChanged();
    #endregion
		
		public MPMINFRUANGANDTL()
		{
			this._MPMINFRUANGANHDR = default(EntityRef<MPMINFRUANGANHDR>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTHRUANGAN", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid IDTHRUANGAN
		{
			get
			{
				return this._IDTHRUANGAN;
			}
			set
			{
				if ((this._IDTHRUANGAN != value))
				{
					if (this._MPMINFRUANGANHDR.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDTHRUANGANChanging(value);
					this.SendPropertyChanging();
					this._IDTHRUANGAN = value;
					this.SendPropertyChanged("IDTHRUANGAN");
					this.OnIDTHRUANGANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPARTICIPANT", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid IDPARTICIPANT
		{
			get
			{
				return this._IDPARTICIPANT;
			}
			set
			{
				if ((this._IDPARTICIPANT != value))
				{
					this.OnIDPARTICIPANTChanging(value);
					this.SendPropertyChanging();
					this._IDPARTICIPANT = value;
					this.SendPropertyChanged("IDPARTICIPANT");
					this.OnIDPARTICIPANTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NPK", DbType="VarChar(50)")]
		public string NPK
		{
			get
			{
				return this._NPK;
			}
			set
			{
				if ((this._NPK != value))
				{
					this.OnNPKChanging(value);
					this.SendPropertyChanging();
					this._NPK = value;
					this.SendPropertyChanged("NPK");
					this.OnNPKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEBY", DbType="VarChar(50)")]
		public string CREATEBY
		{
			get
			{
				return this._CREATEBY;
			}
			set
			{
				if ((this._CREATEBY != value))
				{
					this.OnCREATEBYChanging(value);
					this.SendPropertyChanging();
					this._CREATEBY = value;
					this.SendPropertyChanged("CREATEBY");
					this.OnCREATEBYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATEDATE
		{
			get
			{
				return this._CREATEDATE;
			}
			set
			{
				if ((this._CREATEDATE != value))
				{
					this.OnCREATEDATEChanging(value);
					this.SendPropertyChanging();
					this._CREATEDATE = value;
					this.SendPropertyChanged("CREATEDATE");
					this.OnCREATEDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODIFBY", DbType="VarChar(50)")]
		public string MODIFBY
		{
			get
			{
				return this._MODIFBY;
			}
			set
			{
				if ((this._MODIFBY != value))
				{
					this.OnMODIFBYChanging(value);
					this.SendPropertyChanging();
					this._MODIFBY = value;
					this.SendPropertyChanged("MODIFBY");
					this.OnMODIFBYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODIFDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> MODIFDATE
		{
			get
			{
				return this._MODIFDATE;
			}
			set
			{
				if ((this._MODIFDATE != value))
				{
					this.OnMODIFDATEChanging(value);
					this.SendPropertyChanging();
					this._MODIFDATE = value;
					this.SendPropertyChanged("MODIFDATE");
					this.OnMODIFDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MPMINFRUANGANHDR_MPMINFRUANGANDTL", Storage="_MPMINFRUANGANHDR", ThisKey="IDTHRUANGAN", OtherKey="IDTHRUANGAN", IsForeignKey=true)]
		public MPMINFRUANGANHDR MPMINFRUANGANHDR
		{
			get
			{
				return this._MPMINFRUANGANHDR.Entity;
			}
			set
			{
				MPMINFRUANGANHDR previousValue = this._MPMINFRUANGANHDR.Entity;
				if (((previousValue != value) 
							|| (this._MPMINFRUANGANHDR.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MPMINFRUANGANHDR.Entity = null;
						previousValue.MPMINFRUANGANDTLs.Remove(this);
					}
					this._MPMINFRUANGANHDR.Entity = value;
					if ((value != null))
					{
						value.MPMINFRUANGANDTLs.Add(this);
						this._IDTHRUANGAN = value.IDTHRUANGAN;
					}
					else
					{
						this._IDTHRUANGAN = default(System.Guid);
					}
					this.SendPropertyChanged("MPMINFRUANGANHDR");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
